language: c
dist: trusty
sudo: required

compiler:
  - gcc
  - clang

before_install:
  - tool/travis-ci/before-install

before_script:
  - tool/travis-ci/before-script

script:
  - tool/travis-ci/build
